
# Basic
basictitle: 沐  澄
subtitle: 沐浴阳光.茁壮澄长
## 底部状态栏描述
descriptionDate: 2021-10-19
description: 记录小朋友一岁后的生活日记
# 头像里面的标题
avatarTitle: Only
# 首页里面的描述
avatarDesc: 漂亮小姑娘的成长日记
greeting: 愿你所求皆如愿 所行化坦途 多喜乐 长安宁。

# 博客是否自动生成目录，false为不生成
enableToc: true

# 菜单栏
# 图标地址 http://www.fontawesome.com.cn/
nav:
  - {title: 归档, description: about, url: '/',class: 'fa fa-tags'}
  - {title: 相册, description: tags, url: '/images',class: 'fa fa-picture-o'}
  - {title: 关于, description: comments, url: '/about',class: 'fa fa-lemon-o'}

# 相册列表
imageList:
  - {title: 标题1, intro: 113311, date: '2021-09-27', url: '/assets/20210927',namelist: [1,3,5]}
  - {title: 标题2, intro: 2222, date: '2021-09-30', url: '/assets/20210930',namelist: [2,4]}
  - {title: 标题3, intro: 2222, date: '2021-09-30', url: '/assets/20210930',namelist: [2,4]}
  - {title: 标题4, intro: 2222, date: '2021-09-30', url: '/assets/20210930',namelist: [2,4]}

#permalink: /:year/:month/:title/

# Format
highlighter: rouge
cover_color: clear

plugins:
  - jekyll-feed

# 分页
# 每页有几个项目
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
