
# Basic
basictitle: 沐  澄
subtitle: 沐浴阳光.茁壮澄长
## 底部状态栏描述
descriptionDate: 2021-10-19
description: 记录小朋友一岁后的生活日记
# 头像里面的标题
avatarTitle: Only
# 首页里面的描述
avatarDesc: 漂亮小姑娘的成长日记
greeting: 愿你所求皆如愿 所行化坦途 多喜乐 长安宁。

# 博客是否自动生成目录，false为不生成
enableToc: false

# 菜单栏
# 图标地址 http://www.fontawesome.com.cn/
nav:
  - {title: 归档, description: about, url: '/',class: 'fa fa-tags'}
  - {title: 旅游图册, description: tags, url: '/images',class: 'fa fa-picture-o'}
  - {title: 宝宝相薄, description: tags, url: '/star',class: 'fa fa-star'}
  - {title: 关于, description: comments, url: '/about',class: 'fa fa-lemon-o'}

## baby 秋天的糖炒栗 冬天的烤红薯 春天的樱花树 夏天的冰淇淋
babyList:
    - { title: 一年四季。, intro: 春、夏、秋、冬。, datetime: '2021-09-27', imgUrl: '/assets/Seasons/home',imagehome: home.jpg,imageList: 4 }
    - { title: 春宜花。, intro: 春天的樱花树。, datetime: '2021-09-27', imgUrl: '/assets/Seasons/spring',imagehome: 1.jpg,imageList: 7 }
    - { title: 夏宜风。, intro: 夏天的冰淇淋。, datetime: '2021-09-27', imgUrl: '/assets/Seasons/summer',imagehome: 2.jpg,imageList: 36 }
    - { title: 秋宜月。, intro: 秋天的糖炒栗。, datetime: '2021-09-27', imgUrl: '/assets/Seasons/autumn',imagehome: 3.jpg,imageList: 17 }
    - { title: 冬宜雪。, intro: 冬天的烤红薯 。, datetime: '2021-09-27', imgUrl: '/assets/Seasons/winter',imagehome: 4.jpg,imageList: 46 }
# 相册列表
imageList:
  - {title: 北京篇, intro: 旅游日记-北京篇。, datetime: '2021-09-27', imgUrl: '/assets/beijing',imagehome:  1.jpg,imageList: 6}
  - {title: 成都篇, intro: 旅游日记-成都篇。, datetime: '2021-09-27', imgUrl: '/assets/chengdu',imagehome:  1.jpg,imageList: 9}
  - {title: 神农架篇, intro: 旅游日记-神农架篇。, datetime: '2021-09-27', imgUrl: '/assets/shennongjia',imagehome:  1.jpg,imageList: 3}
  - {title: 泰国篇, intro: 旅游日记-泰国篇。, datetime: '2021-09-27', imgUrl: '/assets/taiguo',imagehome:  1.jpg,imageList: 12}
  - {title: 武汉篇, intro: 旅游日记-武汉篇。, datetime: '2021-09-27', imgUrl: '/assets/wuhan',imagehome:  1.jpg,imageList: 6}
  - {title: 云南篇, intro: 旅游日记-云南篇。, datetime: '2021-09-27', imgUrl: '/assets/yunnan',imagehome:  1.jpg,imageList: 9}

#permalink: /:year/:1_month/:title/

# Format
highlighter: rouge
cover_color: clear

plugins:
  - jekyll-feed

# 分页
# 每页有几个项目
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
